### ISSUE TITLE
feat: implement signup codes

### ISSUE THREAD

**Issue by DMouayad** [DMouayad/healing-guide-api#26]
### Database tables

`signup_codes`:
- id
- user_identifier
- expires_at
- username
- code

#### Step 1

User enters his information:
email or phone number, full name, gender, password. 
We store these info on device storage

#### Step 2

User choose how he want to receive a signup code, either throw an email or a sms.

Client app sends a POST request to `/auth/signup-codes/` where request body should contain the user identifier(an email address or a phone number).

Server creates a TOTP and stores it in the db along side the user identifier(email/phoneNo)
then sends this TOTP to the user.

#### Step 3

User is prompted to enter the signup code he received then the client app sends a POST request to `/auth/signup` with a request body containing user info and the signup code.

**Comment by DMouayad** [comment]
### Tasks:

- [x] create `signup_codes` table migration.
- [x] create `SignupCodesRepository` with methods(store, findByUserIdentifier)
- [x] create endpoint `/auth/signup-codes/`
- [x] add method `verifyCredentialsAreUnique` to `IUserRepository`
- [x] modify `/auth/signup` endpoint:
      - The request body should contain a signup code.
      - Validate the provided signup code against the stored one.
